// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.migrations
{
    [DbContext(typeof(Ger3ahContext))]
    [Migration("20220914160330_AddingTheGer3ahNamesANdLogs")]
    partial class AddingTheGer3ahNamesANdLogs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("API.Entities.Ger3ahLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CraetedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PickedName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PickerName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ger3ahLogs");
                });

            modelBuilder.Entity("API.Entities.Ger3ahName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfPicking")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTaken")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("userIdId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("userIdId");

                    b.ToTable("Ger3ahNames");
                });

            modelBuilder.Entity("API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Entities.Ger3ahName", b =>
                {
                    b.HasOne("API.Entities.User", "userId")
                        .WithMany()
                        .HasForeignKey("userIdId");

                    b.Navigation("userId");
                });
#pragma warning restore 612, 618
        }
    }
}
